server:
  port: 6081
spring:
  #MySQL配置
  datasource:
    url: jdbc:mysql://localhost:3306/noodles?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis配置
  redis:
    host: 192.168.1.103
    database: 5
  #RabbitMq配置
  rabbitmq:
    host: 192.168.1.103
    port: 5672
    username: mzaxd
    password: 200712

mybatis-plus:
  #打印SQL日志 建议生产环境关掉 否则日志爆炸
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
pagehelper:
  auto-dialect: on
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
logging:
  level:
    com.mzaxd.noodles: debug

